<?php

function hobbyImage(string $file, int $w, int $h, string $altTh, string $altEn, ?string $pos = null): array {
  $image = [
    'src'    => 'assets/images/hobbies/' . $file . '?v=' . @filemtime(__DIR__ . '/../assets/images/hobbies/' . $file),
    'w'      => $w,
    'h'      => $h,
    'alt_th' => $altTh,
    'alt_en' => $altEn,
  ];
  if ($pos !== null) {
    $image['pos'] = $pos;
  }
  return $image;
}

function getHobbies(): array {
  return [
    [
      'id'       => 'reading',
      'title_th' => 'อ่านหนังสือ',
      'title_en' => 'Reading',
      'desc_th'  => 'เวลาว่างผมชอบอ่านหนังสือครับ โดยเฉพาะเรื่องที่เกี่ยวกับเทคโนโลยีและการพัฒนาตัวเอง บางครั้งก็ชอบหาบทความหรือเรื่องใหม่ ๆ มาอ่านเพิ่มเติม เพราะรู้สึกว่ายังมีอะไรอีกเยอะที่เราไม่รู้ การได้ใช้เวลาเงียบ ๆ นั่งอ่านหนังสือ นอกจากจะช่วยให้ผ่อนคลายแล้ว บางทีก็ได้ไอเดียใหม่ ๆ กลับมาใช้กับงานด้วยครับ',
      'desc_en'  => 'I enjoy reading in my free time, especially books about technology and personal development. I also like exploring articles and learning about things I haven\'t come across before. Reading gives me a chance to slow down, clear my mind, and sometimes even find new ideas that I can bring into my work.',
      'images'   => [
        hobbyImage('reading-1.jpg', 900, 1200,
          'นั่งอ่านหนังสือในร้านหนังสือที่มีชั้นหนังสือเรียงสูง',
          'Reading a book in a bookstore lined with tall shelves'),
        hobbyImage('reading-2.jpg', 900, 1200,
          'โต๊ะทำงานกับแล็ปท็อปที่เปิดโค้ด และแท็บเล็ตที่วาดไดอะแกรม',
          'A desk with a laptop showing code and a tablet with a sketched diagram'),
        hobbyImage('reading-3.jpg', 900, 1200,
          'นั่งทำงานกับแล็ปท็อปและดูข้อมูลในโทรศัพท์',
          'Working on a laptop while checking a phone'),
        hobbyImage('reading-4.jpg', 900, 1200,
          'แล็ปท็อปบนโต๊ะไม้ในมุมทำงานของร้านกาแฟ',
          'A laptop on a wooden table in a café work corner'),
      ],
    ],
    [
      'id'       => 'running',
      'title_th' => 'วิ่ง',
      'title_en' => 'Running',
      'desc_th'  => 'อีกหนึ่งกิจกรรมที่ผมชอบก็คือการวิ่งครับ ส่วนใหญ่จะออกไปวิ่งช่วงเย็นหลังเลิกงาน เพราะเป็นช่วงที่ได้พักสมองจากการนั่งทำงานมาทั้งวัน บางวันก็วิ่งได้เยอะ บางวันก็วิ่งแค่ระยะสั้น ๆ แล้วแต่สภาพร่างกาย ผมไม่ได้เน้นว่าต้องทำเวลาให้ดีทุกครั้ง แค่อยากออกไปวิ่งให้สม่ำเสมอและได้เห็นตัวเองพัฒนาขึ้นเรื่อย ๆ ครับ',
      'desc_en'  => 'Running is one of my favorite ways to unwind after work. I usually go for an evening run to clear my head after spending most of the day in front of a computer. Some days I run longer, while other days I keep it short. I\'m not always focused on speed or breaking records. I just enjoy staying consistent and seeing myself improve over time.',
      'images'   => [
        hobbyImage('running-1.jpg', 900, 1200,
          'เซลฟี่ในเสื้อวิ่งกลางแจ้ง ท้องฟ้าสีฟ้า',
          'Selfie in a running shirt under a blue sky'),
        hobbyImage('running-2.jpg', 674, 1200,
          'สรุปผลการวิ่งจาก Strava ระยะ 5.03 กิโลเมตร',
          'Strava summary of a 5.03 km run', 'center top'),
        hobbyImage('running-3.jpg', 900, 1200,
          'ทางเดินไม้ริมน้ำที่เปิดไฟยามค่ำคืน',
          'A lit waterfront boardwalk at night'),
        hobbyImage('running-4.jpg', 900, 1200,
          'ทางเดินยกระดับที่เปิดไฟตอนพลบค่ำ มีตึกเมืองอยู่ด้านหลัง',
          'An elevated walkway lit at dusk with the city skyline behind'),
        hobbyImage('running-5.jpg', 900, 1200,
          'ป้ายงาน HYROX Bangkok',
          'The HYROX Bangkok event sign'),
        hobbyImage('running-6.jpg', 900, 1200,
          'เส้นทางวิ่งริมน้ำตอนพระอาทิตย์ตก',
          'A waterfront running path at sunset'),
        hobbyImage('running-7.jpg', 900, 1200,
          'เซลฟี่หน้ากระจกในเสื้อวิ่งสีส้ม',
          'Mirror selfie in an orange running shirt'),
        hobbyImage('running-8.jpg', 900, 1200,
          'นักวิ่งหลายคนวิ่งบนลู่วิ่งในสวนสาธารณะ',
          'Runners on a park running track'),
      ],
    ],
    [
      'id'       => 'gym',
      'title_th' => 'เข้ายิม',
      'title_en' => 'Gym',
      'desc_th'  => 'ผมชอบออกกำลังกายและเล่นเวทครับ เพราะนอกจากจะช่วยให้ร่างกายแข็งแรงแล้ว ยังเป็นอีกหนึ่งกิจกรรมที่ผมรู้สึกสนุกทุกครั้งที่ได้ทำ ผมชอบความรู้สึกเวลาที่ตัวเองสามารถยกน้ำหนักได้มากขึ้นหรือทำสิ่งที่เมื่อก่อนทำไม่ได้ ถึงบางวันจะเหนื่อยหรือไม่ค่อยมีแรง แต่พอได้เห็นพัฒนาการของตัวเองก็รู้สึกว่าคุ้มค่ากับเวลาที่เสียไปครับ',
      'desc_en'  => 'I really enjoy going to the gym and lifting weights. Besides staying healthy, I love seeing myself get stronger and being able to do things I couldn\'t do before. Some days are harder than others, but looking back at how much I\'ve improved always makes the effort worth it. It\'s something I genuinely enjoy and want to keep getting better at.',
      'images'   => [
        hobbyImage('gym-1.jpg', 613, 1200,
          'เซลฟี่หน้ากระจกในยิม',
          'Mirror selfie at the gym', 'center 40%'),
        hobbyImage('gym-2.jpg', 900, 1200,
          'เซลฟี่หน้ากระจกข้างชั้นวางดัมเบล',
          'Mirror selfie beside a dumbbell rack'),
        hobbyImage('gym-3.jpg', 900, 1200,
          'กำลังเล่นเครื่องดึงบาร์ลงในยิม',
          'Working out on a lat pulldown machine'),
      ],
    ],
    [
      'id'       => 'hiking',
      'title_th' => 'เดินเขา',
      'title_en' => 'Hiking',
      'desc_th'  => 'ถ้ามีโอกาสผมก็ชอบออกไปเดินเขาครับ โดยเฉพาะการขึ้นไปชมพระอาทิตย์ตกจากมุมสูง ระหว่างทางก็มีเหนื่อยบ้าง ต้องหยุดพักเป็นระยะ แต่พอเดินขึ้นไปถึงข้างบนแล้วได้เห็นวิวกว้าง ๆ กับแสงอาทิตย์ช่วงเย็น ก็รู้สึกว่าหายเหนื่อยไปเลย ผมชอบบรรยากาศแบบนี้มาก เพราะนอกจากจะได้ออกกำลังกายแล้ว ยังได้ออกไปสัมผัสธรรมชาติและถ่ายรูปสวย ๆ กลับมาด้วยครับ',
      'desc_en'  => 'Whenever I get the chance, I love going hiking, especially when there\'s a beautiful sunset waiting at the top. The climb can be tiring, and sometimes I need to stop and catch my breath, but reaching the viewpoint makes it all worth it. I really enjoy being surrounded by nature, getting some exercise, and taking photos of the scenery along the way.',
      'images'   => [
        hobbyImage('hiking-1.jpg', 900, 1200,
          'เซลฟี่มุมต่ำระหว่างเดินขึ้นเขา',
          'Low-angle selfie on a hike'),
        hobbyImage('hiking-2.jpg', 900, 1200,
          'เส้นทางเดินขึ้นเขาท่ามกลางต้นไม้',
          'A hiking trail through the trees'),
        hobbyImage('hiking-3.jpg', 900, 1200,
          'ทางเดินในป่าที่มีใบไม้ร่วงเต็มพื้น',
          'A forest path scattered with fallen leaves'),
        hobbyImage('hiking-4.jpg', 1200, 900,
          'พระอาทิตย์ตกเหนือเมืองจากยอดเขา มีธงชาติไทยอยู่ด้านหน้า',
          'Sunset over the city from a hilltop, with a Thai flag in front', '25% center'),
      ],
    ],
    [
      'id'       => 'travel',
      'title_th' => 'ท่องเที่ยว',
      'title_en' => 'Travel',
      'desc_th'  => 'ผมเป็นคนชอบเที่ยวครับ ถ้ามีวันหยุดหรือมีเวลาว่างก็มักจะหาสถานที่ใหม่ ๆ ไปอยู่เสมอ ไม่ว่าจะเป็นเที่ยวต่างจังหวัดหรือต่างประเทศ ผมชอบทั้งการวางแผนเดินทาง การได้ลองกินอาหารที่ไม่เคยกิน และการเดินสำรวจสถานที่ต่าง ๆ บางทริปก็วางแผนไว้ละเอียด แต่บางครั้งก็แค่อยากออกไปเที่ยวแบบไม่ต้องคิดอะไรมาก ได้ถ่ายรูปและเก็บประสบการณ์ใหม่ ๆ กลับมาก็มีความสุขแล้วครับ',
      'desc_en'  => 'I love traveling, and whenever I have some free time, I\'m usually looking for somewhere new to visit. Whether it\'s a short trip somewhere in Thailand or traveling abroad, I enjoy planning trips, trying new food, and exploring different places. Sometimes I plan everything in advance, while other times I just go with the flow. For me, traveling is all about enjoying the experience and collecting memories along the way.',
      'images'   => [
        hobbyImage('travel-1.jpg', 900, 1200,
          'เซลฟี่ชูสองนิ้วที่สนามบิน',
          'Peace-sign selfie at the airport'),
        hobbyImage('travel-2.jpg', 900, 1200,
          'ถือหนังสือเดินทางและบัตรขึ้นเครื่องใต้หลังคากระจกของสนามบิน',
          'Holding a passport and boarding pass under the airport’s glass roof'),
        hobbyImage('travel-3.jpg', 900, 1200,
          'ถนนคนเดินที่มีผู้คนมากมายระหว่างบ้านไม้เก่า',
          'A crowded walking street between old wooden houses'),
        hobbyImage('travel-4.jpg', 900, 1200,
          'ชายหาดที่มีต้นมะพร้าวและร่มชายหาด',
          'A beach with coconut palms and beach umbrellas'),
      ],
    ],
    [
      'id'       => 'cafe',
      'title_th' => 'คาเฟ่',
      'title_en' => 'Cafés',
      'desc_th'  => 'อีกอย่างที่ผมชอบคือการไปคาเฟ่ครับ เวลามีวันหยุดก็มักจะลองหาร้านกาแฟใหม่ ๆ ไปนั่ง บางร้านก็ไปเพราะบรรยากาศดี บางร้านก็อยากลองกาแฟ หรือบางทีก็แค่อยากเปลี่ยนที่นั่งพักผ่อน ผมชอบร้านที่ไม่วุ่นวายมาก สามารถนั่งดื่มกาแฟ ฟังเพลง หรือหยิบหนังสือขึ้นมาอ่านได้เรื่อย ๆ เป็นอีกหนึ่งวิธีพักผ่อนง่าย ๆ ที่ผมชอบครับ',
      'desc_en'  => 'I enjoy exploring different cafés whenever I have some free time. Sometimes I visit a place because of its atmosphere, sometimes for the coffee, and sometimes just because I want somewhere different to relax. I especially like quiet cafés where I can enjoy a cup of coffee, listen to music, or read a book without feeling rushed. It\'s one of my favorite ways to spend a day off.',
      'images'   => [
        hobbyImage('cafe-1.jpg', 900, 1200,
          'ถือแก้วเครื่องดื่มเย็นในคาเฟ่ที่มีสวนเขียวและภูเขาด้านหลัง',
          'Holding an iced drink at a café with a green garden and hills behind'),
        hobbyImage('cafe-2.jpg', 900, 1200,
          'คาเฟ่ขนาดใหญ่ที่ตกแต่งด้วยเรือใบ',
          'A large café decorated with a sailing ship'),
        hobbyImage('cafe-3.jpg', 900, 1200,
          'เครื่องดื่มในลูกสับปะรดและแก้วโซดาบนถาดไม้',
          'A drink served in a pineapple beside a glass of soda on a wooden tray'),
        hobbyImage('cafe-4.jpg', 900, 1200,
          'ถือแก้วเครื่องดื่มท็อปวิปครีม',
          'Holding a drink topped with whipped cream'),
        hobbyImage('cafe-5.jpg', 900, 1200,
          'วิวทะเลและชายหาดจากคาเฟ่บนที่สูง',
          'A view of the sea and beach from a hillside café'),
        hobbyImage('cafe-6.jpg', 900, 1200,
          'เรือที่จอดประดับหน้าคาเฟ่',
          'A boat on display in front of a café'),
        hobbyImage('cafe-7.jpg', 900, 1200,
          'ชาเย็นแก้วใหญ่บนโต๊ะเหล็กริมระเบียง',
          'A large iced tea on a metal table by the balcony'),
      ],
    ],
    [
      'id'       => 'food',
      'title_th' => 'กิน',
      'title_en' => 'Food',
      'desc_th'  => 'ผมเป็นคนชอบกินครับ โดยเฉพาะเวลาได้ออกไปลองร้านอาหารใหม่ ๆ กับเพื่อนหรือคนสนิท ไม่ว่าจะเป็นร้านเล็ก ๆ ข้างทางหรือร้านอาหารที่ตั้งใจไปลอง บางครั้งก็ขับรถไปไกลเพียงเพราะอยากกินร้านนั้นโดยเฉพาะ สำหรับผมการได้กินของอร่อย ๆ พร้อมกับพูดคุยกับคนที่ไปด้วย เป็นหนึ่งในกิจกรรมที่มีความสุขและช่วยให้หายเหนื่อยจากการทำงานได้ดีเลยครับ',
      'desc_en'  => 'I\'m a big fan of good food, especially when I get to try new restaurants with friends or people close to me. It doesn\'t matter whether it\'s a small street food spot or a restaurant I\'ve been wanting to visit. Sometimes I\'ll even drive quite far just to try a particular place. For me, enjoying a good meal with great company is one of the best ways to relax after a busy week.',
      'images'   => [
        hobbyImage('food-1.jpg', 900, 1200,
          'หม้อชาบูพร้อมผักและเครื่องเคียงหลายจาน',
          'A hot pot with vegetables and many side dishes'),
        hobbyImage('food-2.jpg', 900, 1200,
          'นั่งปิ้งย่างกินกับเพื่อน ๆ',
          'Grilling and eating with friends'),
        hobbyImage('food-3.jpg', 1200, 900,
          'ชุดซาชิมิแซลมอนและทูน่า',
          'A platter of salmon and tuna sashimi'),
        hobbyImage('food-4.jpg', 900, 1200,
          'ชั้นวางขนมปังและเบเกอรี่',
          'Shelves of bread and pastries'),
        hobbyImage('food-5.jpg', 900, 1200,
          'จานผักสด เส้นขนมจีน และหมูย่าง',
          'A plate of fresh vegetables, rice noodles, and grilled pork'),
        hobbyImage('food-6.jpg', 900, 1200,
          'อาหารจานเล็กเรียงเต็มโต๊ะบุฟเฟต์',
          'Small plates lined up across a buffet table'),
        hobbyImage('food-7.jpg', 900, 1200,
          'ร้านอาหารริมทางที่มีเครื่องปรุงวางเรียงเต็มร้าน',
          'A street food stall lined with toppings and condiments'),
        hobbyImage('food-8.jpg', 900, 1200,
          'ขนมปังและอาหารจานเดียวบนโต๊ะร้านอาหาร',
          'Bread and a plated dish on a restaurant table'),
      ],
    ],
    [
      'id'       => 'gardening',
      'title_th' => 'ปลูกต้นไม้',
      'title_en' => 'Gardening',
      'desc_th'  => 'เวลาที่อยู่บ้านผมก็ชอบปลูกต้นไม้ครับ โดยเฉพาะการปลูกไม้ผลที่ต้องคอยดูแลไปเรื่อย ๆ ตั้งแต่ต้นยังเล็กจนเริ่มออกดอกและติดผล บางต้นก็โตเร็ว บางต้นก็ต้องใช้เวลานานหน่อย แต่พอได้เห็นต้นไม้ที่ปลูกเองค่อย ๆ เติบโตจนสามารถเก็บผลมากินได้ ก็รู้สึกดีเหมือนกันครับ เป็นงานอดิเรกที่ไม่ต้องรีบร้อนอะไร แค่คอยดูแลและรอดูว่ามันจะเติบโตไปได้แค่ไหน',
      'desc_en'  => 'I also enjoy gardening when I\'m at home, especially growing fruit trees. I like taking care of them and watching them grow from small plants until they eventually start producing fruit. Some grow quickly, while others take much longer, but there\'s something really satisfying about finally harvesting fruit from a tree I\'ve grown myself. It\'s a relaxing hobby that teaches me to be patient and enjoy the little things.',
      'images'   => [
        hobbyImage('gardening-1.jpg', 900, 1200,
          'ถือตะกร้ามะม่วงที่เพิ่งเก็บจากต้น',
          'Holding a basket of freshly picked mangoes'),
        hobbyImage('gardening-2.jpg', 900, 1200,
          'มองขึ้นไปที่ต้นไม้ใหญ่ข้างบ้าน',
          'Looking up at a large tree beside the house'),
        hobbyImage('gardening-3.jpg', 900, 1200,
          'สวนต้นไม้ที่ปลูกไว้หน้าบ้าน',
          'A garden of young trees planted in front of the house'),
      ],
    ],
  ];
}
