<?php

function pathImage(string $file, int $w, int $h, string $altTh, string $altEn, ?string $pos = null): array {
  $image = [
    'src'    => 'assets/images/path/' . $file . '?v=' . @filemtime(__DIR__ . '/../assets/images/path/' . $file),
    'w'      => $w,
    'h'      => $h,
    'alt_th' => $altTh,
    'alt_en' => $altEn,
  ];
  if ($pos !== null) {
    $image['pos'] = $pos;
  }
  return $image;
}

function getLifePath(): array {
  return [
    [
      'id'       => 'kindergarten',
      'title_th' => 'อนุบาล',
      'title_en' => 'Kindergarten',
      'desc_th'  => 'ย้อนกลับไปตอนอนุบาลครับ ช่วงนั้นชีวิตก็ไม่ได้มีอะไรซับซ้อนเลย ตื่นเช้าไปโรงเรียน เจอเพื่อน เล่นของเล่น แล้วก็รอเวลากลับบ้าน เป็นช่วงวัยที่ยังไม่ต้องคิดเรื่องอะไรมาก มีความสุขกับเรื่องง่าย ๆ ในแต่ละวัน พอได้กลับมาดูรูปเก่า ๆ ก็อดยิ้มไม่ได้เหมือนกันครับ เพราะหลาย ๆ เรื่องในตอนนั้นก็กลายเป็นความทรงจำที่น่ารักจนถึงวันนี้',
      'desc_en'  => 'Looking back at my kindergarten days, life was pretty simple. Going to school, playing with friends, and waiting for the school day to end were probably my biggest concerns back then. I didn\'t have much to worry about and could enjoy all the little things. Seeing these old photos now always brings a smile to my face.',
      'images'   => [
        pathImage('kindergarten-1.jpg', 1200, 775,
          'เด็กอนุบาลใส่ชุดไทยยืนรวมกลุ่มกันในงานของโรงเรียน',
          'Kindergarten children in Thai costumes at a school event'),
        pathImage('kindergarten-2.jpg', 799, 1200,
          'ภาพถ่ายตอนเด็กใส่แว่นและเสื้อสีขาว',
          'A childhood portrait wearing glasses and a white shirt', 'center 30%'),
        pathImage('kindergarten-3.jpg', 800, 1200,
          'ภาพถ่ายตอนเด็กใส่เสื้อยืดสกรีนตัวอักษร',
          'A childhood portrait in a printed t-shirt', 'center 30%'),
      ],
    ],
    [
      'id'       => 'primary',
      'title_th' => 'ประถม',
      'title_en' => 'Primary School',
      'desc_th'  => 'พอขึ้นประถมก็เริ่มมีอะไรให้ทำมากขึ้นครับ ทั้งเรื่องเรียน กิจกรรมของโรงเรียน และการได้รู้จักเพื่อนใหม่ ๆ ผมมีโอกาสได้ลองทำกิจกรรมหลายอย่าง และเริ่มมีความทรงจำร่วมกับเพื่อนในห้องมากขึ้น ไม่ว่าจะเป็นช่วงพักกลางวัน การเล่นหลังเลิกเรียน หรือกิจกรรมต่าง ๆ ที่โรงเรียนจัดขึ้น พอมองย้อนกลับไปก็คิดถึงบรรยากาศตอนนั้นเหมือนกันครับ',
      'desc_en'  => 'Primary school was when life started getting a little busier. There were more classes, school activities, and plenty of new friends to meet. I got to try different things and made so many memories with my classmates, from playing during lunch breaks to joining school events. Looking back, those were some really fun and carefree years of my childhood.',
      'images'   => [
        pathImage('primary-1.jpg', 1200, 806,
          'นั่งกอดอกถ่ายรูปในห้องตอนเด็ก',
          'Sitting with arms folded in a room as a child'),
        pathImage('primary-2.jpg', 1200, 900,
          'ใส่ชุดนักเรียนยกมือทั้งสองข้างให้กล้อง',
          'In a school uniform, raising both hands for the camera'),
        pathImage('primary-3.jpg', 1200, 900,
          'ร่วมกิจกรรมกลางแจ้งกับเพื่อน ๆ ที่โรงเรียน',
          'At an outdoor school activity with friends'),
        pathImage('primary-4.jpg', 560, 480,
          'ถ่ายรูปกับเพื่อนและตุ๊กตา',
          'With friends and stuffed toys'),
      ],
    ],
    [
      'id'       => 'junior',
      'title_th' => 'มัธยมต้น',
      'title_en' => 'Lower Secondary',
      'desc_th'  => 'ช่วงมัธยมต้นเป็นช่วงที่ผมเริ่มโตขึ้นและเริ่มมีความสนใจของตัวเองมากขึ้นครับ เพื่อนกลายเป็นส่วนสำคัญของชีวิตไปเลย ทั้งไปโรงเรียน ทำกิจกรรม และใช้เวลาว่างด้วยกัน ช่วงนั้นก็ได้ลองทำอะไรหลายอย่าง เริ่มรู้ว่าตัวเองชอบอะไรและไม่ชอบอะไร ถึงตอนนั้นจะยังไม่ได้คิดเรื่องอนาคตจริงจังมากนัก แต่ก็เป็นช่วงเวลาที่มีความทรงจำดี ๆ กับเพื่อนเยอะมากครับ',
      'desc_en'  => 'Lower secondary school was when I started growing up and discovering more about myself. Friends became a huge part of my everyday life, whether we were studying, joining school activities, or just hanging out together. I started exploring different interests and figuring out what I liked and didn\'t like. I wasn\'t thinking too seriously about the future yet, but I made a lot of great memories during those years.',
      'images'   => [
        pathImage('junior-1.jpg', 1200, 900,
          'ถือพานดอกไม้ในพิธีของโรงเรียน',
          'Holding a flower tray at a school ceremony'),
        pathImage('junior-2.jpg', 760, 760,
          'เซลฟี่กับเพื่อน ๆ ในชุดนักเรียน',
          'A selfie with friends in school uniforms'),
        pathImage('junior-3.jpg', 640, 640,
          'เซลฟี่ในเสื้อกีฬาของโรงเรียน',
          'A selfie in a school sports shirt'),
      ],
    ],
    [
      'id'       => 'senior',
      'title_th' => 'มัธยมปลาย',
      'title_en' => 'Upper Secondary',
      'desc_th'  => 'พอขึ้นมัธยมปลายก็เริ่มรู้สึกว่าต้องจริงจังกับชีวิตมากขึ้นครับ เพราะเป็นช่วงที่ต้องเริ่มคิดแล้วว่าเรียนจบไปอยากทำอะไรต่อ แต่ก็ยังมีเรื่องสนุก ๆ อีกเยอะ ทั้งกีฬาสี กิจกรรมของโรงเรียน และการเรียน รด. ที่ได้ทำร่วมกับเพื่อน ๆ มีทั้งวันที่เหนื่อย วันที่สนุก และวันที่เจอเรื่องที่ไม่เป็นไปตามแผน พอได้ย้อนกลับมาดูรูปตอนนั้นก็รู้สึกว่าเป็นอีกหนึ่งช่วงชีวิตที่มีเรื่องให้นึกถึงเยอะมากครับ',
      'desc_en'  => 'Upper secondary school was when I started thinking more seriously about my future and what I wanted to do after graduation. But there were still plenty of fun moments, from sports day and school activities to military cadet training with my friends. Some days were exhausting, while others were full of laughter. Looking back at these photos reminds me of how many great memories I made during those years.',
      'images'   => [
        pathImage('senior-1.jpg', 469, 625,
          'นั่งอยู่ที่ระเบียงอาคารเรียนในชุดนักเรียน',
          'Sitting on a school corridor in uniform', 'center 35%'),
        pathImage('senior-2.jpg', 960, 720,
          'ถ่ายรูปกับเพื่อน ๆ พร้อมลูกโป่งในงานกีฬาสี',
          'With friends and balloons on sports day'),
        pathImage('senior-3.jpg', 540, 960,
          'ยืนถ่ายรูปในเสื้อกีฬาสีของโรงเรียน',
          'Standing in a school sports day shirt', 'center 25%'),
        pathImage('senior-4.jpg', 960, 720,
          'ฝึกภาคสนามของนักศึกษาวิชาทหารกับเพื่อน ๆ',
          'Cadet field training with friends'),
        pathImage('senior-5.jpg', 654, 960,
          'ยืนทำความเคารพในเครื่องแบบนักศึกษาวิชาทหาร',
          'Standing at salute in a cadet uniform', 'center 40%'),
      ],
    ],
    [
      'id'       => 'university',
      'title_th' => 'มหาวิทยาลัย',
      'title_en' => 'University',
      'desc_th'  => 'หลังจากเรียนจบมัธยม ผมก็ได้เข้ามาเรียนที่มหาวิทยาลัยธรรมศาสตร์ ศูนย์รังสิตครับ ช่วงแรกก็ต้องปรับตัวกับอะไรหลายอย่าง ทั้งสภาพแวดล้อมใหม่ เพื่อนใหม่ และการใช้ชีวิตในมหาวิทยาลัย ได้ลองทำกิจกรรมหลายอย่างที่ไม่เคยทำมาก่อน มีทั้งช่วงที่สนุก ช่วงที่เหนื่อย และช่วงที่ต้องรับผิดชอบอะไรด้วยตัวเองมากขึ้น แต่สิ่งที่ชอบที่สุดก็คงเป็นการได้ใช้เวลากับเพื่อน ๆ ทั้งไปเที่ยว ทำกิจกรรม และผ่านช่วงเวลาต่าง ๆ มาด้วยกัน เป็นอีกหนึ่งช่วงชีวิตที่มีความทรงจำดี ๆ เยอะมาก และถ้ามีโอกาสก็อยากกลับไปสัมผัสบรรยากาศแบบนั้นอีกครั้งครับ',
      'desc_en'  => 'After finishing high school, I went to Thammasat University, Rangsit Campus. At first, I had to adjust to a lot of new things, from meeting new friends to getting used to university life. I got to try different activities, take on more responsibilities, and experience things I\'d never done before. But my favorite part was definitely spending time with friends, traveling, joining activities, and making memories together. Looking back, university was one of the most memorable chapters of my life, and I\'d love to experience those days all over again.',
      'images'   => [
        pathImage('university-1.jpg', 790, 1027,
          'ถ่ายรูปตอนกลางคืนในชุดนักศึกษา',
          'A night portrait in a student uniform', 'center 15%'),
        pathImage('university-2.jpg', 914, 1200,
          'เซลฟี่ตอนกลางคืนหน้าตึกสูงในเมือง',
          'A night selfie in front of a city tower', 'center 40%'),
        pathImage('university-3.jpg', 1080, 1080,
          'เดินเที่ยวงานกลางคืนพร้อมกระเป๋าเป้',
          'Walking through an evening fair with a backpack', 'center 35%'),
        pathImage('university-4.jpg', 798, 667,
          'ป้ายมหาวิทยาลัยธรรมศาสตร์ริมถนน',
          'The Thammasat University sign by the road'),
        pathImage('university-5.jpg', 900, 1200,
          'หนังสือเตรียมสอบ TOEIC',
          'A TOEIC reading practice book', 'center 35%'),
      ],
    ],
    [
      'id'       => 'graduation',
      'title_th' => 'รับปริญญา',
      'title_en' => 'Graduation',
      'desc_th'  => 'ในที่สุดก็มาถึงวันรับปริญญาครับ หลังจากใช้เวลาเรียนและทำโปรเจกต์มาตลอดหลายปี ก็เรียนจบปริญญาตรีจากมหาวิทยาลัยธรรมศาสตร์ได้สำเร็จ วันที่ได้รับปริญญาก็รู้สึกดีใจและภูมิใจมาก โดยเฉพาะการได้ถ่ายรูปกับครอบครัวและเพื่อน ๆ ที่อยู่ด้วยกันมาตลอด เป็นอีกหนึ่งวันที่ผมอยากเก็บภาพและความทรงจำเอาไว้ เพราะกว่าจะมาถึงวันนี้ก็ผ่านอะไรกันมาเยอะเหมือนกันครับ',
      'desc_en'  => 'Finally, graduation day arrived! After years of studying, coding, and working on countless projects, I graduated with a Bachelor\'s degree from Thammasat University. It was such a special day, especially getting to celebrate with my family and friends who had been there throughout the journey. Looking at these photos reminds me of all the hard work, late nights, and great memories that brought me to this moment.',
      'images'   => [
        pathImage('graduation-1.jpg', 698, 805,
          'ถ่ายรูปวันรับปริญญาหน้าทุ่งทานตะวัน',
          'A graduation day photo in front of a sunflower field', 'center 20%'),
        pathImage('graduation-2.jpg', 675, 1200,
          'ถือปกปริญญาบัตรสีแดงที่มีตราสีทอง',
          'Holding a red diploma folder with a gold emblem', 'center 45%'),
        pathImage('graduation-3.jpg', 900, 1200,
          'บรรยากาศในหอประชุมระหว่างพิธี มองจากที่นั่งของบัณฑิต',
          'The auditorium during the ceremony, seen from the graduates’ seats'),
        pathImage('graduation-4.jpg', 900, 1200,
          'เวทีและแถวบัณฑิตในหอประชุมระหว่างพิธี',
          'The stage and rows of graduates during the ceremony'),
        pathImage('graduation-5.jpg', 1016, 578,
          'ขณะขึ้นรับปริญญาบัตรบนเวที',
          'Receiving the degree on stage', 'right center'),
      ],
    ],
    [
      'id'       => 'work',
      'title_th' => 'ทำงาน',
      'title_en' => 'Work',
      'desc_th'  => 'หลังจากเรียนจบ ผมก็เริ่มต้นชีวิตการทำงานในตำแหน่ง Software Engineer ครับ จากที่เคยเขียนโปรแกรมเพื่อส่งงานอาจารย์ ก็เปลี่ยนมาเป็นการพัฒนาระบบที่มีคนใช้งานจริงในบริษัท ซึ่งแตกต่างจากตอนเรียนพอสมควร เพราะนอกจากจะต้องเขียนโค้ดให้ทำงานได้แล้ว ยังต้องเข้าใจปัญหาและความต้องการของผู้ใช้งานด้วย แต่ละโปรเจกต์ก็มีความท้าทายแตกต่างกันออกไป มีทั้งปัญหาที่แก้ได้ง่าย ๆ และบางเรื่องที่ต้องใช้เวลาหาวิธีแก้กันหลายวัน ถึงจะมีเหนื่อยบ้าง แต่ผมก็ยังรู้สึกสนุกกับการได้สร้างระบบใหม่ ๆ และได้เห็นผลงานของตัวเองถูกนำไปใช้งานจริงครับ',
      'desc_en'  => 'After graduating, I started my career as a Software Engineer. Going from writing code for university assignments to building systems that people actually use at work was a big change. I quickly learned that being a developer isn\'t just about writing code. It\'s also about understanding users, solving real problems, and finding ways to make things work better. Every project comes with different challenges. Some problems are easy to solve, while others take days to figure out. Even though the work can be challenging, I genuinely enjoy building new systems and seeing people use something I\'ve created.',
      'images'   => [
        pathImage('work-1.jpg', 900, 1200,
          'ใส่เสื้อเชิ้ตสีขาวถ่ายรูปก่อนเข้าทำงาน',
          'In a white shirt before heading in to work', 'center 35%'),
        pathImage('work-2.jpg', 900, 1200,
          'ถ่ายรูปที่โต๊ะทำงานในออฟฟิศ',
          'At my desk in the office'),
        pathImage('work-3.jpg', 672, 917,
          'ถ่ายรูปรับใบประกาศร่วมกับเพื่อนร่วมงาน',
          'Receiving a certificate alongside a colleague'),
        pathImage('work-4.jpg', 1200, 900,
          'เข้าร่วมงานสัมมนาในห้องประชุมใหญ่',
          'Attending a seminar in a large conference hall'),
      ],
    ],
  ];
}
